# Code generated by go.einride.tech/sage. DO NOT EDIT.
# To learn more, see .sage/sagefile.go and https://github.com/einride/sage.

.DEFAULT_GOAL := all

sagefile := .sage/bin/sagefile

.PHONY: $(sagefile)
$(sagefile):
	@cd .sage && go mod tidy && go run .

.PHONY: sage
sage: $(sagefile)

.PHONY: update-sage
update-sage:
	@cd .sage && go get -d go.einride.tech/sage@latest && go mod tidy && go run .

.PHONY: clean-sage
clean-sage:
	@git clean -fdx .sage/tools .sage/bin .sage/build

.PHONY: all
all: $(sagefile)
	@$(sagefile) All

.PHONY: convco-check
convco-check: $(sagefile)
	@$(sagefile) ConvcoCheck

.PHONY: format-markdown
format-markdown: $(sagefile)
	@$(sagefile) FormatMarkdown

.PHONY: format-yaml
format-yaml: $(sagefile)
	@$(sagefile) FormatYAML

.PHONY: git-verify-no-diff
git-verify-no-diff: $(sagefile)
	@$(sagefile) GitVerifyNoDiff

.PHONY: go-generate
go-generate: $(sagefile)
	@$(sagefile) GoGenerate

.PHONY: go-mod-tidy
go-mod-tidy: $(sagefile)
	@$(sagefile) GoModTidy

.PHONY: go-review
go-review: $(sagefile)
	@$(sagefile) GoReview

.PHONY: go-test
go-test: $(sagefile)
	@$(sagefile) GoTest

.PHONY: golangci-lint
golangci-lint: $(sagefile)
	@$(sagefile) GolangciLint

.PHONY: stringer
stringer: $(sagefile)
	@$(sagefile) Stringer

.PHONY: proto
proto:
	$(MAKE) -C proto -f Makefile
