# Code generated by Mage-tools. DO NOT EDIT.

.DEFAULT_GOAL := all

include .mage/tools.mk

.PHONY: all
all: $(mage)
	@$(mage) all

.PHONY: buf-generate-testdata
buf-generate-testdata: $(mage)
	@$(mage) bufGenerateTestdata

.PHONY: convco-check
convco-check: $(mage)
ifndef rev
	$(error missing argument rev="...")
endif
	@$(mage) convcoCheck $(rev)

.PHONY: format-markdown
format-markdown: $(mage)
	@$(mage) formatMarkdown

.PHONY: git-verify-no-diff
git-verify-no-diff: $(mage)
	@$(mage) gitVerifyNoDiff

.PHONY: go-mod-tidy
go-mod-tidy: $(mage)
	@$(mage) goModTidy

.PHONY: go-stringer
go-stringer: $(mage)
	@$(mage) goStringer

.PHONY: go-test
go-test: $(mage)
	@$(mage) goTest

.PHONY: golangci-lint
golangci-lint: $(mage)
	@$(mage) golangciLint

.PHONY: goreview
goreview: $(mage)
	@$(mage) goreview

.PHONY: protoc-gen-go-aip
protoc-gen-go-aip: $(mage)
	@$(mage) protocGenGoAip

.PHONY: proto
proto:
	make -C proto
