// Code generated by "stringer -type MethodType -trimprefix MethodType"; DO NOT EDIT.

package aipreflect

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[MethodTypeNone-0]
	_ = x[MethodTypeGet-1]
	_ = x[MethodTypeList-2]
	_ = x[MethodTypeCreate-3]
	_ = x[MethodTypeUpdate-4]
	_ = x[MethodTypeDelete-5]
	_ = x[MethodTypeUndelete-6]
	_ = x[MethodTypeBatchGet-7]
	_ = x[MethodTypeBatchCreate-8]
	_ = x[MethodTypeBatchUpdate-9]
	_ = x[MethodTypeBatchDelete-10]
	_ = x[MethodTypeSearch-11]
}

const _MethodType_name = "NoneGetListCreateUpdateDeleteUndeleteBatchGetBatchCreateBatchUpdateBatchDeleteSearch"

var _MethodType_index = [...]uint8{0, 4, 7, 11, 17, 23, 29, 37, 45, 56, 67, 78, 84}

func (i MethodType) String() string {
	if i < 0 || i >= MethodType(len(_MethodType_index)-1) {
		return "MethodType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _MethodType_name[_MethodType_index[i]:_MethodType_index[i+1]]
}
